import '../../r1-alpha33/src/app.js';
import { supabase } from '../../r1-alpha17/src/supabase.js';

const VERSION='r1.0.0-alpha.34';
const versionNode=document.querySelector('#app-version');if(versionNode)versionNode.textContent=VERSION;
const nav=document.querySelector('#module-nav');
const content=document.querySelector('#module-content');

function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function fmtDate(v){if(!v)return '—';const [y,m,d]=String(v).slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:String(v);}
function esc(v){return String(v??'');}
function requestId(){return 'h24_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,10);}
function ensureStyle(){if(document.querySelector('#alpha34-style'))return;const s=document.createElement('style');s.id='alpha34-style';s.textContent=`
.h24-shell{display:grid;gap:14px}.h24-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.h24-progress{height:7px;background:#e5edf2;border-radius:999px;overflow:hidden}.h24-progress>span{display:block;height:100%;background:#075985;transition:width .16s ease}.h24-context{position:sticky;top:0;z-index:4;display:flex;gap:18px;justify-content:space-between;flex-wrap:wrap;padding:10px 12px;border:1px solid #dbe5ec;border-radius:10px;background:#fff}.h24-context strong{color:#075985}.h24-card{border:1px solid #dbe5ec;border-radius:14px;padding:14px;background:#fff}.h24-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.h24-wide{grid-column:1/-1}.h24-card label{display:grid;gap:5px;font-weight:700}.h24-card input,.h24-card select,.h24-card textarea{width:100%;box-sizing:border-box;min-height:44px;padding:9px 10px;border:1px solid #aebdca;border-radius:10px;background:#fff;font:inherit}.h24-card textarea{min-height:90px}.h24-check{display:flex!important;grid-template-columns:none!important;align-items:flex-start;gap:9px;padding:10px;border:1px solid #dbe5ec;border-radius:10px;font-weight:500!important}.h24-check input{width:20px;height:20px;min-height:0;flex:0 0 auto;margin-top:1px}.h24-nav{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;position:sticky;bottom:0;padding:10px 0;background:linear-gradient(180deg,rgba(255,255,255,.45),#fff 25%)}.h24-status{padding:11px 12px;border-radius:10px;background:#f1f7fa}.h24-status.danger{background:#fff1f2;color:#991b1b}.h24-status.success{background:#f0fdf4;color:#166534}.h24-summary{display:grid;gap:8px}.h24-summary-row{display:grid;grid-template-columns:160px 1fr;gap:10px;padding:8px;border-bottom:1px solid #e5edf2}.h24-badge{display:inline-flex;padding:4px 8px;border-radius:999px;background:#eef6fb;font-size:.85rem}.h24-step-title{margin:0 0 10px}.h24-open-list{display:grid;gap:8px;margin-top:8px}.h24-open-item{padding:9px 10px;border:1px solid #dbe5ec;border-radius:10px;background:#fff}.h24-manual{display:flex;gap:8px;flex-wrap:wrap}.h24-hidden{display:none!important}@media(max-width:700px){.h24-grid{grid-template-columns:1fr}.h24-wide{grid-column:auto}.h24-summary-row{grid-template-columns:1fr}.h24-nav .button{flex:1 1 150px}}
`;document.head.append(s);}ensureStyle();

async function render24H(){
  content.replaceChildren();
  const shell=el('section',null,'h24-shell');
  const head=el('div',null,'h24-head');const title=el('div');title.append(el('p','Asistencia en carretera','eyebrow'),el('h2','Activar 24H'),el('div','Flujo recuperado de Beta 2.0 · v36 y conectado a metrogestion-pruebas.','muted'));
  const manualBox=el('div',null,'h24-manual');const manual=el('button','📄 Manual 24H','button secondary compact');manual.type='button';manual.onclick=()=>window.open('../Manual_24H_DFM_v2_1.pdf','_blank','noopener');manualBox.append(manual);head.append(title,manualBox);shell.append(head);
  const progress=el('div',null,'h24-progress');const fill=el('span');progress.append(fill);const stepLabel=el('div','Paso 1 de 7 · Identificar vehículo','muted');shell.append(stepLabel,progress);
  const context=el('div',null,'h24-context');const ctxD=el('span');ctxD.append(el('span','Vehículo activo','muted'),document.createElement('br'),el('strong','DFM —'));const ctxM=el('span');ctxM.append(el('span','Matrícula','muted'),document.createElement('br'),el('strong','—'));context.append(ctxD,ctxM);shell.append(context);
  const card=el('section',null,'h24-card');const notice=el('div','', 'h24-status h24-hidden');shell.append(card,notice);const navBox=el('div',null,'h24-nav');const prev=el('button','← Paso anterior','button secondary');prev.type='button';const next=el('button','Siguiente →','button primary');next.type='button';navBox.append(prev,next);shell.append(navBox);content.append(shell);

  const {data:fleetData,error:fleetError}=await supabase.from('vehiculos').select('id,dfm,matricula,categoria,clase_vehiculo,tipo_motor,marca,modelo,bastidor,upc,telefono,fecha_matriculacion,fin_contrato_fecha,fin_contrato_km,km_actual,reserva,activo').eq('activo',true).order('dfm');
  if(fleetError){notice.textContent='No se pudieron cargar los vehículos: '+fleetError.message;notice.className='h24-status danger';return;}
  const fleet=fleetData||[];const byDfm=new Map(fleet.map(v=>[String(v.dfm),v]));let current=0;let vehicle=null;let activationId=null;let coverageOk=false;
  const state={};
  const stepNames=['Identificar vehículo','Seguridad · Procedimiento 0','Ubicación y avería','Revisar datos para comunicar','Contrato y llamada','Registrar activación','Seguimiento'];
  const showNotice=(msg,type='')=>{notice.textContent=msg;notice.className='h24-status'+(type?' '+type:'');};const clearNotice=()=>{notice.textContent='';notice.className='h24-status h24-hidden';};
  const setContext=()=>{ctxD.querySelector('strong').textContent=vehicle?`DFM ${vehicle.dfm}`:'DFM —';ctxM.querySelector('strong').textContent=vehicle?.matricula||'—';};
  const inp=(id,label,type='text',value='')=>{const l=el('label');l.append(el('span',label));const i=document.createElement('input');i.id=id;i.type=type;i.value=value??'';l.append(i);return[l,i];};
  const sel=(id,label,options,value='')=>{const l=el('label');l.append(el('span',label));const s=document.createElement('select');s.id=id;options.forEach(([v,t])=>s.append(new Option(t,v)));s.value=value;l.append(s);return[l,s];};
  const ta=(id,label,value='')=>{const l=el('label');l.append(el('span',label));const t=document.createElement('textarea');t.id=id;t.value=value??'';l.append(t);return[l,t];};
  const check=(id,text,checked=false)=>{const l=el('label',null,'h24-check');const i=document.createElement('input');i.type='checkbox';i.id=id;i.checked=checked;l.append(i,el('span',text));return[l,i];};
  const parseKm=v=>{const n=Number(String(v||'').replace(/\D/g,''));return Number.isFinite(n)?n:0;};
  const evaluateCoverage=()=>{if(!vehicle)return{ok:false,text:'Selecciona un vehículo.'};const km=parseKm(state.km_actual??vehicle.km_actual);const limit=Number(vehicle.fin_contrato_km||0);const today=new Date();today.setHours(0,0,0,0);const end=vehicle.fin_contrato_fecha?new Date(vehicle.fin_contrato_fecha+'T00:00:00'):null;const kmOk=!limit||!km||km<=limit;const dateOk=!end||today<=end;coverageOk=kmOk&&dateOk;const parts=[];parts.push(limit?`KM: ${km.toLocaleString('es-ES')} / ${limit.toLocaleString('es-ES')}`:'KM: sin límite configurado');parts.push(end?`Fin contrato: ${fmtDate(vehicle.fin_contrato_fecha)}`:'Fin contrato: sin fecha configurada');return{ok:coverageOk,text:parts.join(' · ')};};
  const buildSummary=()=>[['DFM',vehicle?.dfm],['Matrícula',vehicle?.matricula],['Marca / modelo',[vehicle?.marca,vehicle?.modelo].filter(Boolean).join(' ')],['Bastidor',vehicle?.bastidor],['UPC',vehicle?.upc],['Conductor',state.conductor],['Teléfono',state.telefono],['Ubicación',state.ubicacion],['Avería',state.averia],['Código alarma',state.codigo_alarma],['Carga',state.carga]];
  const collectPayload=()=>({dfm:String(vehicle?.dfm||''),matricula:vehicle?.matricula||'',marca:vehicle?.marca||'',modelo:vehicle?.modelo||'',bastidor:vehicle?.bastidor||'',upc:vehicle?.upc||'',km_actual:String(parseKm(state.km_actual||vehicle?.km_actual)||''),contrato_km:String(vehicle?.fin_contrato_km||''),fin_contrato_fecha:vehicle?.fin_contrato_fecha||'',cobertura_ok:String(coverageOk),conductor:state.conductor||'',telefono_conductor:state.telefono||'',ubicacion_tipo:state.ubicacion_tipo||'',ubicacion_referencia:state.ubicacion||'',carretera:state.carretera||'',punto_km:state.punto_km||'',sentido:state.sentido||'',averia:state.averia||'',codigo_alarma:state.codigo_alarma||'',color_alarma:state.color_alarma||'',semirremolque:state.semirremolque||'',carga:state.carga||'',numero_caso:state.numero_caso||'',hora_activacion:state.hora_activacion||'',eta_tecnico:state.eta_tecnico||'',proveedor:state.proveedor||'',tecnico_llegado:String(Boolean(state.tecnico_llegado)),hora_llegada:state.hora_llegada||'',diagnostico_confirmado:String(Boolean(state.diagnostico_confirmado)),diagnostico:state.diagnostico||'',reparado_carretera:String(Boolean(state.reparado_carretera)),trasladado_taller:String(Boolean(state.trasladado_taller)),taller_traslado:state.taller_traslado||'',estado_operativo_confirmado:String(Boolean(state.estado_operativo_confirmado)),resultado:state.resultado||'seguimiento_abierto',estado:state.resultado==='reparado_carretera'?'cerrada':'abierta'});
  const saveActivation=async()=>{const {data,error}=await supabase.rpc('guardar_activacion_24h',{p_id:activationId,p_payload:collectPayload(),p_request_id:requestId()});if(error)throw error;activationId=data?.id||activationId;return data;};

  function renderStep(){clearNotice();card.replaceChildren();fill.style.width=`${((current+1)/7)*100}%`;stepLabel.textContent=`Paso ${current+1} de 7 · ${stepNames[current]}`;prev.disabled=current===0;next.textContent=current===6?'Guardar seguimiento':'Siguiente →';
    if(current===0){card.append(el('h3','¿Qué vehículo necesita asistencia?','h24-step-title'));const [ld,dfm]=inp('h24-dfm','DFM o matrícula');dfm.setAttribute('list','h24-fleet');dfm.placeholder='Ej. 2521 o 1850MLJ';const dl=document.createElement('datalist');dl.id='h24-fleet';fleet.forEach(v=>dl.append(new Option(`DFM ${v.dfm} · ${v.matricula||''}`,String(v.dfm))));const [lk,km]=inp('h24-km','Kilómetros actuales','text',state.km_actual??vehicle?.km_actual??'');km.inputMode='numeric';const grid=el('div',null,'h24-grid');grid.append(ld,lk);card.append(grid,dl);if(vehicle){const info=el('div',null,'h24-status');info.textContent=`${vehicle.marca||'—'} ${vehicle.modelo||''} · Bastidor ${vehicle.bastidor||'—'} · UPC ${vehicle.upc||'—'} · contrato ${vehicle.fin_contrato_km?Number(vehicle.fin_contrato_km).toLocaleString('es-ES')+' km':'sin km'} · ${fmtDate(vehicle.fin_contrato_fecha)}`;card.append(info);}dfm.value=vehicle?.dfm||'';dfm.onchange=()=>{const raw=dfm.value.toUpperCase().replace(/^DFM\s*/,'').split('·')[0].trim();vehicle=byDfm.get(raw)||fleet.find(v=>String(v.matricula||'').toUpperCase()===raw)||null;state.km_actual=vehicle?.km_actual||'';setContext();renderStep();};km.oninput=()=>{state.km_actual=km.value;};}
    if(current===1){card.append(el('h3','Procedimiento 0','h24-step-title'));const [a,ca]=check('h24-safe','Vehículo detenido en lugar seguro o correctamente señalizado',state.safe);const [b,cb]=check('h24-people','Conductor y ocupantes fuera de peligro',state.people);const [c,cc]=check('h24-loadok','Se ha comprobado si la carga está afectada',state.loadChecked);const [ln,n]=inp('h24-driver','Conductor','text',state.conductor||'');const [lp,p]=inp('h24-phone','Teléfono del conductor','tel',state.telefono||vehicle?.telefono||'');const grid=el('div',null,'h24-grid');grid.append(ln,lp);card.append(a,b,c,grid);ca.onchange=()=>state.safe=ca.checked;cb.onchange=()=>state.people=cb.checked;cc.onchange=()=>state.loadChecked=cc.checked;n.oninput=()=>state.conductor=n.value;p.oninput=()=>state.telefono=p.value;}
    if(current===2){card.append(el('h3','Ubicación y avería','h24-step-title'));const [lt,t]=sel('h24-ltype','Tipo de ubicación',[['abrera','Bloque logístico Abrera'],['sansa','Bloque logístico Sansa'],['disfrimur','Nave Disfrimur'],['industrial','Polígono'],['store','Tienda'],['road','Carretera / autopista / autovía'],['other','Otro']],state.ubicacion_tipo||'abrera');const [lr,r]=inp('h24-location','Ubicación / Plus Code / coordenadas','text',state.ubicacion||'');const [la,a]=ta('h24-fault','Descripción literal del aviso',state.averia||'');const [lc,c]=inp('h24-alarm','Código de alarma','text',state.codigo_alarma||'');const [lcol,col]=sel('h24-color','Color del aviso',[['','Sin testigo'],['Amarillo','Amarillo'],['Rojo','Rojo'],['Otro','Otro']],state.color_alarma||'');const [ltr,tr]=inp('h24-trailer','Semirremolque','text',state.semirremolque||'');const [lload,load]=sel('h24-load','Carga',[['Sin carga','Sin carga'],['Con carga','Con carga'],['Tractora suelta','Tractora suelta']],state.carga||'Sin carga');const road=el('div',null,'h24-grid h24-wide');const [lroad,roadn]=inp('h24-road','Carretera','text',state.carretera||'');const [lpk,pk]=inp('h24-pk','Punto kilométrico','text',state.punto_km||'');const [ls,sen]=inp('h24-dir','Sentido','text',state.sentido||'');road.append(lroad,lpk,ls);const grid=el('div',null,'h24-grid');grid.append(lt,lr,la,lc,lcol,ltr,lload,road);card.append(grid);const toggle=()=>road.classList.toggle('h24-hidden',t.value!=='road');toggle();t.onchange=()=>{state.ubicacion_tipo=t.value;toggle();if(t.value==='abrera')r.value='GV6V+62 Abrera';if(t.value==='sansa')r.value="CRJ3+HG Sant Sadurní d'Anoia";if(t.value==='disfrimur')r.value="CRM4+G2 Sant Sadurní d'Anoia";state.ubicacion=r.value;};r.oninput=()=>state.ubicacion=r.value;a.oninput=()=>state.averia=a.value;c.oninput=()=>state.codigo_alarma=c.value;col.onchange=()=>state.color_alarma=col.value;tr.oninput=()=>state.semirremolque=tr.value;load.onchange=()=>state.carga=load.value;roadn.oninput=()=>state.carretera=roadn.value;pk.oninput=()=>state.punto_km=pk.value;sen.oninput=()=>state.sentido=sen.value;}
    if(current===3){card.append(el('h3','Datos preparados para comunicar al 24H','h24-step-title'));const s=el('div',null,'h24-summary');buildSummary().forEach(([k,v])=>{const row=el('div',null,'h24-summary-row');row.append(el('strong',k),el('span',v||'—'));s.append(row);});const [lc,c]=check('h24-confirm','He revisado los datos y están preparados para comunicarlos',state.summaryConfirmed);c.onchange=()=>state.summaryConfirmed=c.checked;card.append(s,lc);}
    if(current===4){card.append(el('h3','Contrato y llamada','h24-step-title'));const cov=evaluateCoverage();const box=el('div',null,'h24-status '+(cov.ok?'success':'danger'));box.append(el('strong',cov.ok?'Cobertura correcta':'Cobertura no válida'),document.createElement('br'),el('span',cov.text));card.append(box);const sum=el('div',null,'h24-summary');buildSummary().forEach(([k,v])=>{const row=el('div',null,'h24-summary-row');row.append(el('strong',k),el('span',v||'—'));sum.append(row);});card.append(sum,el('div','Datos preparados para leer al operador. La llamada se realiza según el protocolo interno de la marca.','muted'));}
    if(current===5){card.append(el('h3','Registrar activación','h24-step-title'));const [lc,c]=inp('h24-case','Número de asistencia / caso','text',state.numero_caso||'');const [lh,h]=inp('h24-time','Hora de activación','time',state.hora_activacion||new Date().toTimeString().slice(0,5));const [le,e]=inp('h24-eta','ETA del técnico','time',state.eta_tecnico||'');const [lp,p]=inp('h24-provider','Taller o proveedor asignado','text',state.proveedor||'');const grid=el('div',null,'h24-grid');grid.append(lc,lh,le,lp);card.append(grid,el('div','Al pasar a Seguimiento se guardará la activación real en metrogestion-pruebas.','h24-status'));c.oninput=()=>state.numero_caso=c.value;h.oninput=()=>state.hora_activacion=h.value;e.oninput=()=>state.eta_tecnico=e.value;p.oninput=()=>state.proveedor=p.value;}
    if(current===6){card.append(el('h3','Seguimiento','h24-step-title'));const [la,a]=check('h24-arr','Técnico llegado',state.tecnico_llegado);const [lhat,hat]=inp('h24-arrtime','Hora real de llegada','time',state.hora_llegada||'');const [ld,d]=check('h24-diagok','Diagnóstico confirmado',state.diagnostico_confirmado);const [ldt,dt]=ta('h24-diag','Descripción de la avería confirmada',state.diagnostico||'');const [lr,r]=check('h24-roadfix','Reparado en carretera',state.reparado_carretera);const [lt,t]=check('h24-transfer','Trasladado a taller',state.trasladado_taller);const [lwt,wt]=inp('h24-workshop','Taller de traslado','text',state.taller_traslado||'');const [lo,o]=check('h24-oper','Hora y estado operativo confirmados',state.estado_operativo_confirmado);const [lres,res]=sel('h24-result','Resultado',[['seguimiento_abierto','Seguimiento abierto'],['reparado_carretera','Reparado en carretera'],['trasladado_taller','Trasladado a taller · mantener misma INC'],['necesita_sustitucion','Necesita sustitución']],state.resultado||'seguimiento_abierto');const grid=el('div',null,'h24-grid');grid.append(la,lhat,ld,ldt,lr,lt,lwt,lo,lres);card.append(grid,activationId?el('div',`Activación guardada · ${activationId}`,'h24-status success'):null);a.onchange=()=>state.tecnico_llegado=a.checked;hat.oninput=()=>state.hora_llegada=hat.value;d.onchange=()=>state.diagnostico_confirmado=d.checked;dt.oninput=()=>state.diagnostico=dt.value;r.onchange=()=>{state.reparado_carretera=r.checked;if(r.checked){t.checked=false;state.trasladado_taller=false;res.value='reparado_carretera';state.resultado=res.value;}};t.onchange=()=>{state.trasladado_taller=t.checked;if(t.checked){r.checked=false;state.reparado_carretera=false;res.value='trasladado_taller';state.resultado=res.value;}};wt.oninput=()=>state.taller_traslado=wt.value;o.onchange=()=>state.estado_operativo_confirmado=o.checked;res.onchange=()=>state.resultado=res.value;}
  }

  function validate(){if(current===0){if(!vehicle)return'Selecciona un DFM o matrícula.';if(!parseKm(state.km_actual||vehicle.km_actual))return'Introduce los kilómetros actuales.';const cov=evaluateCoverage();if(!cov.ok)return'El vehículo está fuera de las condiciones de contrato configuradas.';}if(current===1){if(!state.safe)return'Confirma que el vehículo está en un lugar seguro.';if(!state.people)return'Confirma que conductor y ocupantes están fuera de peligro.';const digits=String(state.telefono||'').replace(/\D/g,'');if(digits.length<9||digits.length>15)return'Introduce un teléfono del conductor válido.';}if(current===2){if(!String(state.averia||'').trim())return'Describe la avería.';if(state.ubicacion_tipo==='road'&&(!state.carretera||!state.punto_km||!state.sentido))return'En carretera indica carretera, PK y sentido.';if(!String(state.ubicacion||'').trim()&&!['road'].includes(state.ubicacion_tipo))return'Indica la ubicación.';}if(current===3&&!state.summaryConfirmed)return'Confirma que has revisado los datos.';if(current===4&&!coverageOk)return'No se puede continuar sin cobertura válida.';if(current===5&&!String(state.numero_caso||'').trim())return'Introduce el número de asistencia / caso.';if(current===6){if(state.tecnico_llegado&&!state.hora_llegada)return'Indica la hora real de llegada.';if(state.diagnostico_confirmado&&!String(state.diagnostico||'').trim())return'Escribe el diagnóstico confirmado.';if(state.trasladado_taller&&!String(state.taller_traslado||'').trim())return'Indica el taller de traslado.';}return'';}
  prev.onclick=()=>{if(current>0){current--;renderStep();}};
  next.onclick=async()=>{const err=validate();if(err){showNotice(err,'danger');return;}clearNotice();try{if(current===5){evaluateCoverage();await saveActivation();showNotice('Activación 24H guardada. Continúa con el seguimiento.','success');current=6;renderStep();return;}if(current===6){await saveActivation();showNotice('Seguimiento 24H guardado y auditado.','success');return;}current++;renderStep();}catch(e){showNotice('No se pudo guardar: '+e.message,'danger');}};
  renderStep();
}

function prepareNav(){if(!nav)return;let b=nav.querySelector('[data-alpha34-24h]');if(!b){b=document.createElement('button');b.type='button';b.className='button secondary';b.dataset.alpha34_24h='1';b.setAttribute('data-alpha34-24h','1');b.textContent='🚨 Activar 24H';b.addEventListener('click',e=>{e.preventDefault();[...nav.querySelectorAll('button')].forEach(x=>x.classList.remove('active'));b.classList.add('active');render24H();});nav.prepend(b);}}
if(nav){const ob=new MutationObserver(()=>prepareNav());ob.observe(nav,{childList:true});prepareNav();nav.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.matches('[data-alpha34-24h]'))nav.querySelector('[data-alpha34-24h]')?.classList.remove('active');});}
