-- Pruebas transaccionales; no persisten datos de prueba.
BEGIN;
SET LOCAL statement_timeout='90s';
CREATE TEMP TABLE tmp_2719_fixture ON COMMIT DROP AS SELECT r.id AS registro FROM public.registros_hotel r JOIN public.pizarras p ON p.id=r.pizarra_id WHERE r.seguimiento_id='69b57b1d-95be-451b-a6fe-fac274ba430e' AND p.estado='en_curso';
CREATE TEMP TABLE tmp_2719_resultados(prueba text,resultado jsonb) ON COMMIT DROP;
CREATE TEMP TABLE tmp_2719_original ON COMMIT DROP AS SELECT id,nombre,estado,fecha_real,fecha_inicio_real,fecha_fin_real,cancelado,grupo_documental_id FROM public.etapas_hotel WHERE registro_hotel_id=(SELECT registro FROM tmp_2719_fixture);

DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":3302,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|REPARACION|ACT|2026-02-24","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"REPARACIÓN ","pedido":"","pedido_fondo_amarillo":false,"designacion":"ACT","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-02-24","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3318,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|TM|TRAMITE|EXTINTOR|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"TM","tipo_trabajo":"TRAMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"EXTINTOR","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3319,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|APPLUS VILAFRANCA|TRAMITE|44TN|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"APPLUS VILAFRANCA","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"44TN","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3320,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|APPLUS VILAFRANCA|TRAMITE|ITV|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"APPLUS VILAFRANCA","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"ITV","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3321,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|MANTENIMIENTO|MCD|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"MANTENIMIENTO","pedido":"","pedido_fondo_amarillo":false,"designacion":"MCD","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3324,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|MANTENIMIENTO|MCD|2027-04-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"MANTENIMIENTO","pedido":"","pedido_fondo_amarillo":false,"designacion":"MCD","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2027-04-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>0 OR (resultado->>'trabajos_creados')::integer<>0 THEN RAISE EXCEPTION 'Primera pasada real: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('Primera pasada real',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;


DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":3302,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|REPARACION|ACT|2026-02-24","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"REPARACIÓN ","pedido":"","pedido_fondo_amarillo":false,"designacion":"ACT","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-02-24","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3318,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|TM|TRAMITE|EXTINTOR|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"TM","tipo_trabajo":"TRAMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"EXTINTOR","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3319,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|APPLUS VILAFRANCA|TRAMITE|44TN|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"APPLUS VILAFRANCA","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"44TN","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3320,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|APPLUS VILAFRANCA|TRAMITE|ITV|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"APPLUS VILAFRANCA","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"ITV","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3321,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|MANTENIMIENTO|MCD|2026-10-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"MANTENIMIENTO","pedido":"","pedido_fondo_amarillo":false,"designacion":"MCD","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-10-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":3324,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|AUTODIS|MANTENIMIENTO|MCD|2027-04-23","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"AUTODIS","tipo_trabajo":"MANTENIMIENTO","pedido":"","pedido_fondo_amarillo":false,"designacion":"MCD","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2027-04-23","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>0 OR (resultado->>'trabajos_creados')::integer<>0 THEN RAISE EXCEPTION 'Segunda pasada real: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('Segunda pasada real',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;

DO $test$ BEGIN IF (SELECT count(*) FROM public.etapas_hotel WHERE registro_hotel_id=(SELECT registro FROM tmp_2719_fixture))<>5 THEN RAISE EXCEPTION 'Se recrearon T'; END IF; END $test$;

DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":900001,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|44TN|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"44TN","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":900002,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|ITV|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"ITV","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>1 OR (resultado->>'trabajos_creados')::integer<>2 THEN RAISE EXCEPTION 'ITV y 44TN nuevos comparten T: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('ITV y 44TN nuevos comparten T',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;


DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":900001,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|44TN|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"44TN","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":900002,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|ITV|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"ITV","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"2026-09-17","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>0 OR (resultado->>'trabajos_creados')::integer<>0 THEN RAISE EXCEPTION 'Una sola necesidad realizada: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('Una sola necesidad realizada',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;

DO $test$ BEGIN IF EXISTS (SELECT 1 FROM public.etapas_hotel WHERE registro_hotel_id=(SELECT registro FROM tmp_2719_fixture) AND lugar='PRUEBA AGRUPACION' AND (estado<>'pendiente' OR fecha_real IS NOT NULL)) THEN RAISE EXCEPTION 'Cierre prematuro'; END IF; END $test$;

DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":900001,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|44TN|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"44TN","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"2026-09-18","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":900002,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA AGRUPACION|TRAMITE|ITV|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA AGRUPACION","tipo_trabajo":"TRÁMITE","pedido":"","pedido_fondo_amarillo":false,"designacion":"ITV","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"2026-09-17","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>0 OR (resultado->>'trabajos_creados')::integer<>0 THEN RAISE EXCEPTION 'Ambas necesidades realizadas: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('Ambas necesidades realizadas',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;

DO $test$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.etapas_hotel WHERE registro_hotel_id=(SELECT registro FROM tmp_2719_fixture) AND lugar='PRUEBA AGRUPACION' AND estado='realizada' AND (fecha_real AT TIME ZONE 'Europe/Madrid')::date='2026-09-18') THEN RAISE EXCEPTION 'Fecha conjunta incorrecta'; END IF; END $test$;

DO $test$ DECLARE resultado jsonb; BEGIN
resultado := app_private.manteniment_importar_trabajos($payload$[{"fila":900010,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA TALLER|REPARACIÓN|ACT|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA TALLER","tipo_trabajo":"REPARACIÓN ","pedido":"","pedido_fondo_amarillo":false,"designacion":"ACT","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true},{"fila":900011,"trabajo_sync_id":"","clave_fila":"2719|6132NGV|PRUEBA TALLER|MANTENIMIENTO|MCD|2026-09-16","dfm":"2719","matricula":"6132NGV","numero_parada":"","taller":"PRUEBA TALLER","tipo_trabajo":"MANTENIMIENTO","pedido":"","pedido_fondo_amarillo":false,"designacion":"MCD","marca_vehiculo":"IVECO","marca_equipo":"","fecha_necesidad":"2026-09-16","fecha_realizada":"","fecha_recogida":"","pendiente_fondo_blanco":true,"prioridad_fondo_amarillo":true}]$payload$::jsonb);
IF (resultado->>'t_creadas')::integer<>2 OR (resultado->>'trabajos_creados')::integer<>2 THEN RAISE EXCEPTION 'MCD y ACT comparten entrada y recogida: %',resultado; END IF;
INSERT INTO tmp_2719_resultados VALUES ('MCD y ACT comparten entrada y recogida',resultado);
END $test$;
DROP TABLE tmp_alpha74_manteniment_candidates,tmp_alpha74_manteniment_raw;

DO $test$ BEGIN
IF EXISTS(SELECT 1 FROM tmp_2719_original b LEFT JOIN public.etapas_hotel e ON e.id=b.id WHERE e.id IS NULL OR ROW(e.nombre,e.estado,e.fecha_real,e.fecha_inicio_real,e.fecha_fin_real,e.cancelado,e.grupo_documental_id) IS DISTINCT FROM ROW(b.nombre,b.estado,b.fecha_real,b.fecha_inicio_real,b.fecha_fin_real,b.cancelado,b.grupo_documental_id)) THEN RAISE EXCEPTION 'Se modificó una T original'; END IF;
END $test$;
SET CONSTRAINTS ALL IMMEDIATE;
SELECT jsonb_agg(to_jsonb(t)) as pruebas FROM tmp_2719_resultados t;
ROLLBACK;
