import '../../r1-alpha28/src/app.js';
import { supabase } from '../../r1-alpha17/src/supabase.js';

const VERSION='r1.0.0-alpha.29';
const versionNode=document.querySelector('#app-version');if(versionNode)versionNode.textContent=VERSION;
const nav=document.querySelector('#module-nav');const content=document.querySelector('#module-content');
const HIDE_LABELS=['Hotel real · Previa','Transformación · Previa','Revisión manual','Estados y colores'];

function ensureStyle(){if(document.querySelector('#alpha29-style'))return;const s=document.createElement('style');s.id='alpha29-style';s.textContent=`
.listados-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;flex-wrap:wrap}.listados-filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px;margin:14px 0}.listados-filters label{display:grid;gap:5px;font-weight:700}.listados-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin:12px 0}.listados-metric{border:1px solid #dbe5ec;border-radius:12px;padding:12px;background:#fff}.listados-metric strong{display:block;font-size:1.35rem}.listados-table-wrap{overflow:auto;border:1px solid #dbe5ec;border-radius:12px;background:#fff}.listados-table{width:100%;border-collapse:collapse;min-width:980px}.listados-table th,.listados-table td{padding:9px 10px;border-bottom:1px solid #e5edf2;text-align:left;vertical-align:top}.listados-table th{background:#f1f7fa;position:sticky;top:0;z-index:1}.listados-empty{padding:24px;text-align:center}.listados-print-title{display:none}
@media print{body{background:#fff}.app-header,.session-bar,#module-nav,.listados-controls,.listados-filters{display:none!important}.page-shell{max-width:none!important;margin:0!important;padding:0!important}.module-content{padding:0!important}.listados-print-title{display:block;margin-bottom:12px}.listados-table-wrap{border:0;overflow:visible}.listados-table{min-width:0;font-size:9pt}.listados-table th{position:static;background:#eee!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.listados-table th,.listados-table td{padding:5px 6px}.listados-summary{grid-template-columns:repeat(3,1fr)}@page{size:A4 landscape;margin:10mm}}
`;document.head.append(s);}
function fmtDate(v){if(!v)return '—';const [y,m,d]=String(v).slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:v;}
function stateLabel(v){return ({planificado:'Pendiente de parar',pendiente_taller:'Pendiente de taller',pendiente_diagnostico:'Pendiente diagnóstico',pendiente_autorizacion:'Pendiente autorización',en_taller:'En taller',pendiente_repuestos:'Pendiente repuestos',terminado_pendiente_recogida:'Pendiente de recoger',recogido_pendiente_ruta:'Pendiente de recuperar',recuperado:'Recuperado',anulado:'Anulado'})[v]||v||'—';}
function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
async function renderListados(){ensureStyle();content.replaceChildren();const wrap=el('section');const head=el('div',null,'listados-head');const titleBox=el('div');titleBox.append(el('p','Informes operativos','eyebrow'),el('h2','Listados'));const controls=el('div',null,'listados-controls');const printBtn=el('button','🖨️ Imprimir','button primary');printBtn.type='button';printBtn.onclick=()=>window.print();controls.append(printBtn);head.append(titleBox,controls);wrap.append(head,el('div','Listado de paradas e inmovilización en taller. Una fila por parada real.','muted'));
const printTitle=el('div',null,'listados-print-title');printTitle.append(el('h2','Metrogestión · Listado de paradas'));wrap.append(printTitle);
const filters=el('div',null,'listados-filters');const month=document.createElement('input');month.type='month';month.value='2026-08';const from=document.createElement('input');from.type='date';const to=document.createElement('input');to.type='date';const search=document.createElement('input');search.placeholder='DFM, matrícula o parada';const workshop=document.createElement('input');workshop.placeholder='Taller';for(const [label,input] of [['Mes',month],['Desde',from],['Hasta',to],['Buscar',search],['Taller',workshop]]){const l=el('label');l.append(el('span',label),input);filters.append(l);}wrap.append(filters);
const summary=el('div',null,'listados-summary');const tableWrap=el('div',null,'listados-table-wrap');wrap.append(summary,tableWrap);content.append(wrap);
const {data,error}=await supabase.from('listado_paradas_operativas').select('*').order('fecha_parada',{ascending:false});if(error){tableWrap.append(el('div',`No se pudo cargar Listados: ${error.message}`,'notice danger'));return;}const rows=data||[];
function apply(){let filtered=rows.slice();if(month.value){filtered=filtered.filter(r=>String(r.fecha_parada||'').startsWith(month.value));}if(from.value)filtered=filtered.filter(r=>String(r.fecha_parada||'')>=from.value);if(to.value)filtered=filtered.filter(r=>String(r.fecha_parada||'')<=to.value);const q=search.value.trim().toLowerCase();if(q)filtered=filtered.filter(r=>[r.dfm,r.matricula,r.numero_parada,r.incidencia].some(v=>String(v||'').toLowerCase().includes(q)));const tw=workshop.value.trim().toLowerCase();if(tw)filtered=filtered.filter(r=>String(r.talleres||'').toLowerCase().includes(tw));summary.replaceChildren();const totalDays=filtered.reduce((a,r)=>a+Number(r.dias_taller||0),0);const avg=filtered.length?totalDays/filtered.length:0;for(const [label,val] of [['Paradas',filtered.length],['Días en taller',totalDays.toFixed(1)],['Promedio días/parada',avg.toFixed(1)]]){const m=el('div',null,'listados-metric');m.append(el('strong',String(val)),el('span',label,'muted'));summary.append(m);}printTitle.querySelector('h2').textContent=`Metrogestión · Listado de paradas${month.value?' · '+month.value:''}`;tableWrap.replaceChildren();if(!filtered.length){tableWrap.append(el('div','No hay resultados con estos filtros.','listados-empty'));return;}const table=el('table',null,'listados-table');const thead=el('thead');const hr=el('tr');['Fecha','Parada','DFM','Matrícula','INC','Causa','Estado','Taller','Días taller','UPC'].forEach(h=>hr.append(el('th',h)));thead.append(hr);const tbody=el('tbody');filtered.forEach(r=>{const tr=el('tr');[fmtDate(r.fecha_parada),r.numero_parada||'—',r.dfm||'—',r.matricula||'—',r.incidencia||'—',r.causa||'—',stateLabel(r.estado),r.talleres||r.lugar||'—',Number(r.dias_taller||0).toFixed(1),r.upc||'—'].forEach(v=>tr.append(el('td',String(v))));tbody.append(tr);});table.append(thead,tbody);tableWrap.append(table);}
[month,from,to,search,workshop].forEach(i=>{i.addEventListener('input',apply);i.addEventListener('change',apply);});apply();}

function prepareNav(){if(!nav)return;[...nav.querySelectorAll('button')].forEach(b=>{if(HIDE_LABELS.some(x=>b.textContent.includes(x)))b.remove();});let listBtn=nav.querySelector('[data-alpha29-listados]');if(!listBtn){listBtn=document.createElement('button');listBtn.type='button';listBtn.className='button secondary';listBtn.dataset.alpha29Listados='1';listBtn.textContent='📋 Listados';listBtn.addEventListener('click',e=>{e.preventDefault();[...nav.querySelectorAll('button')].forEach(b=>b.classList.remove('active'));listBtn.classList.add('active');renderListados();});nav.append(listBtn);} }
if(nav){const obs=new MutationObserver(prepareNav);obs.observe(nav,{childList:true,subtree:false});prepareNav();nav.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.dataset.alpha29Listados)queueMicrotask(()=>{nav.querySelector('[data-alpha29-listados]')?.classList.remove('active');});});}
